name: Bug report
description: File a bug report against rubs.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report! Please fill out the sections below to help us reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: Describe the issue including steps to reproduce.
      value: |
        **Description:**

        **Steps to reproduce:**
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected outcome
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What actually happened? Include as much output as possible.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: rubs version
      description: Paste the output of `rubs --version`.
      render: text
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add other context about the problem here, such as OS, terminal, or special setup.
    validations:
      required: false
